### ISSUE TITLE
sqlite3.OperationalError: near "+": syntax error

### ISSUE THREAD

**Issue by seadog007** [gumblex/tg-export#5]
![2017-02-27 00_55_06-my - tmux a - xshell 5 free for home_school](https://cloud.githubusercontent.com/assets/5138409/23341698/6ffd6e26-fc87-11e6-8654-fbbe926fe1d2.png)

**Comment by gumblex** [comment]
What's the SQLite version?

**Comment by seadog007** [comment]
If you are asking the sqlite3 command on my computer
```
> sqlite3
3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d
```

**Comment by gumblex** [comment]
This version doesn't support index on expressions. Should be fixed now.

**Comment by seadog007** [comment]
Thanks
