### ISSUE TITLE
[Feature Request] Added some delay b/w fetching

### ISSUE THREAD

**Issue by seadog007** [gumblex/tg-export#6]
![2017-02-27 15_11_22-my - tmux a - xshell 5 free for home_school](https://cloud.githubusercontent.com/assets/5138409/23351961/6a286a64-fcff-11e6-972e-966973926bd2.png)

**Comment by gumblex** [comment]
I don't understand.

**Comment by seadog007** [comment]
so basically, there were failures when the program fetch every 3000 messages, so I think there should be some delay between every 3000 messages to avoid the failures

**Comment by gumblex** [comment]
The failures are probably due to API rate limit, and there _is_ already some delay for the timeout. I think currently the timeout is sufficient. You can just ignore such errors.
